import type { Metadata } from "next";
import Link from "next/link";

import { LegalLayout, LegalSection } from "@/components/legal/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service · AXL",
  description:
    "The terms that govern your use of AXL's AI beauty analysis.",
};

export default function TermsPage() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Terms of Service"
      intro="These terms govern your use of AXL. By using the service, you agree to them."
      lastUpdated="August 21, 2026"
    >
      <LegalSection title="What AXL is">
        <p>
          AXL provides an AI-generated reading of a photo you supply,
          returning a cosmetic beauty profile, recommendations, and a score. It
          is an informational and entertainment tool designed to help you
          explore styling and grooming choices.
        </p>
      </LegalSection>

      <LegalSection title="Not professional advice">
        <p>
          AXL is <strong>not</strong> a medical, dermatological, or
          psychological service. Its output is a cosmetic estimate produced by
          an AI model and should not be relied upon as professional advice or as
          an objective measure of your appearance, health, or worth. Always
          consult a qualified professional for medical or skincare concerns.
        </p>
      </LegalSection>

      <LegalSection title="AI limitations">
        <p>
          Results are generated by an AI system from a single image and will
          vary with lighting, angle, and image quality. They are approximate and
          may be inaccurate or inconsistent. You should treat every result as
          subjective guidance rather than fact.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>
          You agree to upload only photos of yourself, or images you have the
          right to use with the consent of the person shown. You must not use
          AXL to analyze images of others without permission, to harass or
          demean anyone, or for any unlawful purpose. You should be at least 18,
          or have the consent of a parent or guardian.
        </p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          You are responsible for activity under your account and for keeping
          your sign-in credentials secure. You may delete your saved analyses at
          any time from your <Link href="/account">account page</Link>.
        </p>
      </LegalSection>

      <LegalSection title="Intellectual property">
        <p>
          The AXL name, interface, and generated report design are ours. The
          analysis produced for your photo is provided to you for your personal,
          non-commercial use.
        </p>
      </LegalSection>

      <LegalSection title="Disclaimer &amp; limitation of liability">
        <p>
          AXL is provided &ldquo;as is,&rdquo; without warranties of any
          kind. To the fullest extent permitted by law, we are not liable for
          any indirect, incidental, or consequential damages arising from your
          use of the service or reliance on its output.
        </p>
      </LegalSection>

      <LegalSection title="Changes to these terms">
        <p>
          We may update these terms from time to time. Continued use of AXL
          after changes take effect constitutes acceptance of the revised terms.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these terms? Reach us at{" "}
          <a href="mailto:hello@alkline.com">hello@alkline.com</a> or visit our{" "}
          <Link href="/contact">contact page</Link>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
