import type {
  BeautyProfileAttribute,
  BeautyScoreData,
  FacialAnalysisCardData,
  GlowUpPotentialData,
  ImpactImprovementCardData,
  RecommendationItem,
} from "@/types/results";

/**
 * Builds a plain-text summary of the full beauty consultation —
 * score, glow-up potential, profile, facial analysis, highest-impact
 * improvements, and recommendations. Every value here is passed in
 * from the same AI-generated analysis already rendered on the page;
 * nothing is fabricated at report-build time.
 */
export function buildBeautyReportText(
  score: BeautyScoreData,
  profile: BeautyProfileAttribute[],
  recommendations: RecommendationItem[],
  glowUp?: GlowUpPotentialData,
  impactImprovements?: ImpactImprovementCardData[],
  facialAnalysis?: FacialAnalysisCardData[]
): string {
  const lines: string[] = [];

  lines.push("ALKLINE — BEAUTY REPORT");
  lines.push("Beauty, Personalized by Intelligence.");
  lines.push("");
  lines.push(`Beauty Harmony Score: ${score.score} / 100`);
  lines.push(score.description);

  if (glowUp) {
    lines.push("");
    lines.push("GLOW-UP POTENTIAL");
    lines.push("----------------");
    lines.push(`Current appearance: ${glowUp.currentAppearanceScore} / 100`);
    lines.push(`Improvement potential: ${glowUp.potentialScore} / 100`);
    lines.push(`  ${glowUp.reason}`);
  }

  lines.push("");
  lines.push("BEAUTY PROFILE");
  lines.push("----------------");
  profile.forEach((attribute) => {
    lines.push(`${attribute.label}: ${attribute.value} (${attribute.confidence}% confidence)`);
    lines.push(`  ${attribute.explanation}`);
  });

  if (facialAnalysis && facialAnalysis.length > 0) {
    lines.push("");
    lines.push("COMPLETE FACIAL ANALYSIS");
    lines.push("----------------");
    facialAnalysis.forEach((item) => {
      lines.push(`${item.feature}: ${item.status} (${item.confidence}% confidence)`);
      lines.push(`  ${item.explanation}`);
    });
  }

  if (impactImprovements && impactImprovements.length > 0) {
    lines.push("");
    lines.push("HIGHEST IMPACT IMPROVEMENTS");
    lines.push("----------------");
    impactImprovements.forEach((item) => {
      lines.push(`${item.rank}. ${item.area} — ${item.priority} priority`);
      lines.push(`  ${item.explanation}`);
      lines.push(`  Expected improvement: ${item.expectedImprovement}`);
    });
  }

  lines.push("");
  lines.push("RECOMMENDATIONS");
  lines.push("----------------");
  recommendations.forEach((item) => {
    lines.push(`${item.category}: ${item.value}`);
    lines.push(`  Why: ${item.reason}`);
  });
  lines.push("");
  lines.push("Generated by Alkline AI from your uploaded photo.");

  return lines.join("\n");
}

/** Triggers a client-side download of plain text — no server round trip. */
export function downloadTextFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);

  URL.revokeObjectURL(url);
}
